### PR TITLE
[Update] Namespace from Com.OneSignal to OneSignalSDK.Xamarin

### PR DESCRIPTION
**Pull request by tanaynigam**
# Description
## One Line Summary
Update namespaces, files, and folder names from Com.OneSignal to OneSignalSDK.Xamarin

### Motivation
Updates all namespaces of the core library consisting of Xamarin Android, Xamarin iOS, Xamarin Core, Xamarin OneSignal Default, and Sample apps to incorporate OneSignalSDK.Xamarin instead of Com.OneSignal. These do not include Bindings Libraries which continue using Com.OneSignal as their namespace

### Scope
* Update file, folder and namespace of Xamarin Android from `Com.OneSignal.Android` to `OneSignalSDK.Xamarin.Android`
* Update file, folder and namespace of Xamarin Android from `Com.OneSignal.iOS` to `OneSignalSDK.Xamarin.iOS`
* Update file, folder and namespace of Xamarin Android from `Com.OneSignal.Core` to `OneSignalSDK.Xamarin.Core`
* Update file, folder and namespace of OneSignal Default instance class from `Com.OneSignal` to `OneSignalSDK.Xamarin`
* Update `OneSignalSDK.Xamarin.Core`'s `OneSignalSDK` abstract partial class to `OneSignalSDKInternal`
* Update project and configuration files to reflect namespace changes
* Update nuspec file to relfect namespace changes
* Update nuspec file to change nuget package name to `OneSignal.Xamarin`
* Update file, folder and namespace of Sample Apps from `Com.OneSignal.Sample.Droid`, `Com.OneSignal.Sample.iOS` and `Com.OneSignal.Sample.Shared` to `OneSignalApp.Sample.Droid`, `OneSignalApp.Sample.iOS` and `OneSignalApp.Sample.Shared` respectively
* Update import in Sample Apps from `Com.OneSignal` to `OneSignalSDK.Xamarin`

# Testing
## Manual Testing
* Created a local NuGet package and imported it to a fresh Xamarin App project. Tested `OneSignalSDK.Xamarin` and `OneSignalSDK.Xamarin.Core` import requirements.
* Build and run Xamarin app from a fresh Xamarin App project on Android and iOS devices
* Build and run Xamarin app from OneSignal Sample App project on Android and iOS devices

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285)

### CODE REVIEW

**Review by jkasten2 — COMMENTED** [review]
Code changes themselves look good.
Before approving going run locally to ensure there are no build or configuration issues.

> Reviewed 66 of 66 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-:-MzurmsNAwzyPIeKFCrZ:bq3tnai)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

**Review by jkasten2 — APPROVED** [review]
I tested on an Android 12 emulator and with an iPhone with iOS 14 (NSE w/ action buttons).

Thanks for clear details in the PR looks good to me!

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-:-MzvVKapAZ4yzE_DJXqo:b3t3b3f)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @adamschlesinger)

**Review by adamschlesinger — APPROVED** [review]
> Reviewed 65 of 66 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tanaynigam)

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285)* status: all files reviewed, 4 unresolved discussions (waiting on @tanaynigam)

___
*[OneSignal.Xamarin.nuspec, line 5 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_M9X9CwrIL8mpEINe:-N-_M9XACwoOYc3Rw_iT:b2ycvqq) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L5)):*
> ```XML
>     <metadata>
>         <version>4.0.0</version>
>         <id>OneSignal.Xamarin</id>
> ```

I think we should make this `OneSignalSDK.Xamarin`. This way there is no confusion for app developers the namespace they should be using in their code.
___
*[OneSignal.Xamarin.nuspec, line 44 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_MLcX-2dAabvoe2Lq:-N-_MLcX-2dAabvoe2Lr:bdh5t9b) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L44)):*
> ```XML
> 
>         
>         <file src="OneSignalSDK.Xamarin.Android\bin\Release\*OneSignal.*" target="lib\MonoAndroid10" />
> ```

This needs to be `*OneSignal*` instead of `*OneSignal.*`. Otherwise it will be skipping over our `OneSignalSDK`. We have a mix of "OneSignal" and "OneSignalSDK" so we need to use `*OneSignal*` to get both the internal and public facing assemblies.
___
*[OneSignal.Xamarin.nuspec, line 47 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_MrBx-Eb1DfBKwNxJ:-N-_MrBx-Eb1DfBKwNxK:bl0gb04) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L47)):*
> ```XML
> 
>         
>         <file src="OneSignalSDK.Xamarin.iOS\bin\Release\*OneSignal.*" target="lib\Xamarin.iOS10" />
> ```

Same comment about from Android applies to iOS.
___
*[OneSignal.Xamarin.nuspec, line 52 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_LdT7DtOJa9qYnUnd:-N-_LdT7DtOJa9qYnUne:bk6gtng) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L52)):*
> ```XML
>         
>         <file src="OneSignal.iOS.Binding\bin\Release\OneSignal.iOS.Binding.resources\**" target="content\Com.OneSignal.iOS.resources" />
> ```

The `content` path was updated in `Com.OneSignal.targets`.
This needs to be updated to match. Change this to: `content\OneSignalSDK.Xamarin.iOS.resources`.

This is required otherwise you will get iOS link errors as the framework won't be copied in.

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285)* status: all files reviewed, 5 unresolved discussions (waiting on @tanaynigam)

___
*[OneSignal.Xamarin.nuspec, line 55 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_pifq7tHWAf9zFolf:-N-_pifq7tHWAf9zFolg:bx5v0dj) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L55)):*
> ```XML
>         
>         <file src="OneSignal.iOS.Binding\Com.OneSignal.targets" target="build\Xamarin.iOS10\" />
> ```

Running `nuget pack -properties Configuration=Release` throws the following warning:
```
WARNING: NU5129: - At least one .targets file was found in 'build/Xamarin.iOS10/', but 'build/Xamarin.iOS10/OneSignalSDK.Xamarin.targets' was not.
```

The `Com.OneSignal.targets` file needs to be renamed to `OneSignalSDK.Xamarin.targets` (as this name needs to match the nuget package id).

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285)* status: all files reviewed, 5 unresolved discussions (waiting on @tanaynigam)

___
*[OneSignal.Xamarin.nuspec, line 55 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_pifq7tHWAf9zFolf:-N-a0P8J1-QFPPOiZey2:b-o17omr) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L55)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Running `nuget pack -properties Configuration=Release` throws the following warning:
```
WARNING: NU5129: - At least one .targets file was found in 'build/Xamarin.iOS10/', but 'build/Xamarin.iOS10/OneSignalSDK.Xamarin.targets' was not.
```

The `Com.OneSignal.targets` file needs to be renamed to `OneSignalSDK.Xamarin.targets` (as this name needs to match the nuget package id).
</blockquote></details>

.nuspec has token replacement we could use to prevent some mistakes like this:
https://docs.microsoft.com/en-us/nuget/reference/nuspec#replacement-tokens
It has some build in ones like `id`.

**Review by jkasten2 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285)* status: all files reviewed, 1 unresolved discussion (waiting on @tanaynigam)

___
*[OneSignal.Xamarin.nuspec, line 5 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_M9X9CwrIL8mpEINe:-N-iPmXDDiE78dF9K5Yy:b4a72s8) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L5)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I think we should make this `OneSignalSDK.Xamarin`. This way there is no confusion for app developers the namespace they should be using in their code.
</blockquote></details>

Addressed in PR #286, and it has been merged into this branch now.
___
*[OneSignal.Xamarin.nuspec, line 44 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_MLcX-2dAabvoe2Lq:-N-iPt9X464SVyH_v2oX:b4a72s8) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L44)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This needs to be `*OneSignal*` instead of `*OneSignal.*`. Otherwise it will be skipping over our `OneSignalSDK`. We have a mix of "OneSignal" and "OneSignalSDK" so we need to use `*OneSignal*` to get both the internal and public facing assemblies.
</blockquote></details>

Addressed in PR #286, and it has been merged into this branch now.
___
*[OneSignal.Xamarin.nuspec, line 47 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_MrBx-Eb1DfBKwNxJ:-N-iPugmClhcnlJZNZrX:b4a72s8) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L47)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Same comment about from Android applies to iOS.
</blockquote></details>

Addressed in PR #286, and it has been merged into this branch now.
___
*[OneSignal.Xamarin.nuspec, line 52 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_LdT7DtOJa9qYnUnd:-N-iPvqH9LUnUPPMlker:b4a72s8) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L52)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

The `content` path was updated in `Com.OneSignal.targets`.
This needs to be updated to match. Change this to: `content\OneSignalSDK.Xamarin.iOS.resources`.

This is required otherwise you will get iOS link errors as the framework won't be copied in.
</blockquote></details>

Addressed in PR #286, and it has been merged into this branch now.
___
*[OneSignal.Xamarin.nuspec, line 55 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/285#-N-_pifq7tHWAf9zFolf:-N-iPyuZ-p5sQtXQsjeT:by5002h) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/5b75d7ebf509ac49b2e3dc2d7f93d1e27531b49c/OneSignal.Xamarin.nuspec#L55)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

.nuspec has token replacement we could use to prevent some mistakes like this:
https://docs.microsoft.com/en-us/nuget/reference/nuspec#replacement-tokens
It has some build in ones like `id`.
</blockquote></details>

Addressed in PR #286, and it has been merged into this branch now.
Skipped the suggestion of using `id` may not match as it looks to be based on the project, rather than the nuspec id itself.

**Pull request merged**
